name: ldrift
channels:
  - conda-forge
  - pip
dependencies:
  - python =3.11
  - numpy
  - xarray
  - netcdf4
  - pandas
  - geopandas
  - dask
  - dask-labextension
  - pyarrow
  - shapely
  - numba
  - matplotlib
  - cartopy
  - colormaps
  - cmocean
  - scipy
  - geopy
  - clouddrift
