name: ldrift
channels:
  - conda-forge
dependencies:
  - python =3.11
  - numpy
  - xarray
  - netcdf4
  - pandas
  - geopandas
  - dask
  - dask-labextension
  - pyarrow
  - shapely
  - numba
  - matplotlib
  - mpl_toolkits
  - cartopy
  - colormaps
  - cmocean
  - tqdm
  - scipy
  - sklearn
  - geopy
  - piecewise_regression
  - pwlf
  - itertools
  - os
  - pyproj
  - glob
  - PIL
